# coding=utf8


KAFKA_TOPIC_KEYS = {
    "INSTANCE_CREATE": "INSTANCE.CREATE",   # 用户发起创建实例的请求
    "INSTANCE_SYNC": "IMAGE.SYNC",   # 用户发起同步镜像的请求
    "INSTANCE_ASYNC": "IMAGE.ASYNC",   # 用户发起同步镜像的请求

    "INSTANCE_COLD_MIGRATE": "INSTANCE.COLDMIGRATE",   # 用户发起虚拟机冷迁移的请求
    "INSTANCE_HOT_MIGRATE": "INSTANCE.HOTMIGRATE",   # 用户发起虚拟机热迁移的请求
    "INSTANCE_DISKCONFIG": "INSTANCE.DISKCONFIG",   # 用户发起硬盘新增、修改请求
    "V2V_OPENSTACK":"V2V.OPENSTACK" ,   #v2v OPENSTACK模块
    "INSTANCE_CLONE_CREATE":"INSTANCE.CLONECREATE" ,   #v2v OPENSTACK模块
    "INSTANCE_CLONE":"INSTANCE.CLONE", #instance克隆模块

    "INSTANCE_CREATE_PERFORMANCE":"INSTANCE.PERFORMANCE"  # vishi的性能检测接口

}